version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./configs/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=defender
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=XThwauCbMPcaTkByRGsu
    ports:
      - "5432:5432"

  nginx:
    image: nginx
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"

  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  celery:
    build: 
      context: ./backend/
      dockerfile: celery-dockerfile

    environment:
      - CELERY_BROKER=redis://redis
      - CELERY_BACKEND=redis://redis
      - REDIS_HOST=redis
      - PSQL_HOST=db

