version: "3"

services:
    # db:
    #     image: postgres
    #     restart: always
    #     volumes:
    #         - ./data/db:/var/lib/postgresql/data
    #         - ./configs/init.sql:/docker-entrypoint-initdb.d/init.sql
    #     environment:
    #         - POSTGRES_DB=defender
    #         - POSTGRES_USER=root
    #         - POSTGRES_PASSWORD=XThwauCbMPcaTkByRGsu
    #     ports:
    #         - "5432:5432"

    nginx:
        image: nginx
        volumes:
            - ./configs/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "7777:80"
            # - "443:443"
        restart: always
        depends_on:
            - front
            - api

    front:
        build:
            context: ./defender-frontend/
        restart: always
        command: "npm start"

    redis:
        image: redis
        restart: always
        # ports:
        # - "6379:6379"
        environment:
            - ALLOW_EMPTY_PASSWORD=yes

    api:
        build:
            context: ./backend/

        volumes:
            - ./data/exploits:/exploits

        entrypoint: uvicorn --log-level debug --reload --host 0.0.0.0 --port 8000 api.froutes:app

        environment:
            - CELERY_BROKER=redis://redis
            - CELERY_BACKEND=redis://redis
            - REDIS_HOST=redis
            - PSQL_HOST=home.kochan.fun
            - PSQL_USER=postgres
            - PSQL_PASSWORD=password

    watchers:
        build:
            context: ./backend/

        entrypoint: python3 watchers.py

        volumes:
            - ./data/exploits:/exploits

        environment:
            - CELERY_BROKER=redis://redis
            - CELERY_BACKEND=redis://redis
            - REDIS_HOST=redis
            - PSQL_HOST=home.kochan.fun
            - PSQL_USER=postgres
            - PSQL_PASSWORD=password

    celery:
        build:
            context: ./backend/

        entrypoint: celery -A tasks.tasks worker --loglevel=INFO

        volumes:
            - ./data/exploits:/exploits
            - ./checkers:/checkers

        environment:
            - CELERY_BROKER=redis://redis
            - CELERY_BACKEND=redis://redis
            - REDIS_HOST=redis
            - PSQL_HOST=home.kochan.fun
            - PSQL_USER=postgres
            - PSQL_PASSWORD=password
