version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./configs/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=defender
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=XThwauCbMPcaTkByRGsu
    ports:
      - "5432:5432"

  redis:
    image: redis

