-- +goose Up
-- +goose StatementBegin
SELECT 'up SQL query';


-- CREATE TABLE first_defences (
-- 	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
-- 
-- 	user_id int REFERENCES users (id) ON DELETE CASCADE,
-- 	task_id int REFERENCES tasks (id) ON DELETE CASCADE,
-- 	machine_name text,
-- 
-- 	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
-- );
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
SELECT 'down SQL query';
DROP TABLE first_defences;
-- +goose StatementEnd
