-- +goose Up
-- +goose StatementBegin
SELECT 'up SQL query';

CREATE TABLE checker (
    id serial PRIMARY KEY,
    task_id serial REFERENCES tasks(id) ON DELETE CASCADE,
    
    checker_url text NOT NULL
);

ALTER TABLE tasks DROP COLUMN checker_path;
ALTER TABLE tasks DROP COLUMN tcp_ports_needed;

-- Запуск чекера. Результат нужно ждать в 
CREATE TABLE checker_run (
    id serial PRIMARY KEY,
    check_type text NOT NULL,

    result text DEFAULT NULL,
    ok boolean DEFAULT NULL
);

CREATE TABLE simple_checker_run (
    checker_run_id int PRIMARY KEY REFERENCES checker_run(id) ON DELETE CASCADE,

    target_machine_name text NOT NULL,
    checker_id int REFERENCES checker(id) ON DELETE CASCADE
);


-- TODO isolated_checker_run который инвариант к target_image

-- Связь статуса решенности таска-пользователя и результата проверки
CREATE TABLE first_checker_run (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

	user_id int REFERENCES users (id) ON DELETE CASCADE,
	task_id int REFERENCES tasks (id) ON DELETE CASCADE,
	run_id int REFERENCES checker_run(id) ON DELETE CASCADE,

	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),

	UNIQUE (user_id, run_id)
);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
SELECT 'down SQL query';



-- +goose StatementEnd
