CREATE TABLE users (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username TEXT,
	password TEXT
);

CREATE TABLE tasks (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title TEXT,
	download_url TEXT,
	demo_url TEXT
);

CREATE TABLE solves (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

	user_id int REFERENCES users (id) ON DELETE CASCADE,
	task_id int REFERENCES tasks (id) ON DELETE CASCADE,

	exploit boolean,
	defence boolean
);
