CREATE TABLE users (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username TEXT,
	password TEXT
);

CREATE TABLE tasks (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title TEXT,
	download_url TEXT,
	demo_url TEXT,
	flag TEXT,

	checker_path VARCHAR(1024),
	post_time TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE solves (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

	user_id int REFERENCES users (id) ON DELETE CASCADE,
	task_id int REFERENCES tasks (id) ON DELETE CASCADE,

	exploit boolean,
	defence boolean,

	done_time TIMESTAMP WITH TIME ZONE
);

CREATE TABLE exploits (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

	user_id int REFERENCES users (id) ON DELETE CASCADE,
	task_id int REFERENCES tasks (id) ON DELETE CASCADE,

	path VARCHAR(1024),
	works int DEFAULT -1,
	post_time TIMESTAMP WITH TIME ZONE DEFAULT now()
);
